SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `imagebin` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `imagebin` ;

-- -----------------------------------------------------
-- Table `imagebin`.`Painting`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `imagebin`.`Painting` (
  `shortCode` CHAR(10) CHARACTER SET 'ascii' COLLATE 'ascii_bin' NOT NULL ,
  `booleanIsPublic` BIT(1) NOT NULL ,
  `datetimeCreated` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ,
  PRIMARY KEY (`shortCode`) )
ENGINE = InnoDB
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = ascii
COLLATE = ascii_bin
INSERT_METHOD = FIRST
PACK_KEYS = 0
ROW_FORMAT = FIXED PARTITION BY KEY() PARTITIONS 4;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
